#include "awb/provides/physical_platform.h"

PHYSICAL_DEVICES_CLASS::PHYSICAL_DEVICES_CLASS(
    PLATFORMS_MODULE p) :
    PLATFORMS_MODULE_CLASS(p),
    deviceSwitch(`PLATFORM_ID)
{
}

PHYSICAL_DEVICES_CLASS::~PHYSICAL_DEVICES_CLASS()
{
}
